name: CrossCraft-Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          cd ..
          mv build/Classic-Server Classic-Server
          chmod +x ./Classic-Server
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CC-Server-Linux
          path: |
            Classic-Server
            config.cfg
            LICENSE
            README.md
  
  Mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          cd ..
          mv build/Classic-Server Classic-Server
          chmod +x ./Classic-Server
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CC-Server-Mac
          path: |
            Classic-Server
            config.cfg
            LICENSE
            README.md

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          git submodule update --init --recursive --remote
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          copy ext/zconf.h ext/zlib/zconf.h
          cmake --build . --config Release
          move Release\Classic-Server.exe Classic-Server.exe
          move ZLib\Release\zlib.dll zlib.dll
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CC-Server-Windows
          path: |
            Classic-Server.exe
            config.cfg
            LICENSE
            README.md
            zlib.dll
